### PR TITLE
github-files: add template files to github folder

### LINKED ISSUE #9: Criar um CONTRIBUTING.md
Precisamos criar um `CONTRIBUTING.md` com instruções de como contribuir com o projeto:

- Como instalar e configurar o ambiente de dev
- Apresentar o board: https://github.com/pagarme/react-cards-component/projects/1
- Orientações de como começar uma task e abrir um PR

### PR DESCRIPTION
**Pull request by vcapretz**
closes #9 

in the CONTRIBUTING file there are some stuff that probably need to be discussed:

- is English the main language we should use for communication? (for PRs, issues, code, commits, etc).
It's on almost other pagar.me's repos, but I noticed we are using Portuguese when creating issues.

- is the email that people should use to contact the maintainers "mercurio@pagar.me" or not?

### CODE REVIEW

**Comment by thiagommedeiros** [comment]
Answering your questions:

1 - I think we should use only English for communication.
2 - Maybe we should use the email `developers@pagar.me`, what do you think @grvcoelho @derekstavis?

**Comment by thiagommedeiros** [comment]
teste

**Comment by vcapretz** [comment]
eu estive vendo o fórum sobre isso e o derek respondeu essa dúvida lá: https://github.com/pagarme/forum/issues/84

basicamente: 
- **Issues** - Português
- **Pull Requests** - Português
- **Commits** - Inglês

isso impactaria nos templates de ISSUES e PRs certo? ou mantemos os templates em inglês e discussões em PT?

**Comment by augusto-jm-amaral** [comment]
Acho que podemos manter ao menos os templates em inglês, pois assim um estrangeiro pode saber se determinado bug já foi reportado ou uma feature esta sendo desenvolvida, etc.

**Comment by vcapretz** [comment]
just to be clear, instead of using languages as previously suggest by me, we are going to use English for everything in English _specifically for this project_, because we are intending to make it global by allowing people to add international credit-cards

**Pull request merged**
